DROP ALL OBJECTS;
create table address (id serial primary key, complement varchar(255), latitude varchar(255), longitude varchar(255), neighborhood varchar(255), number varchar(255), public_area varchar(255), zip_code varchar(255), city_id integer, user_id integer, primary key (id));
create table balance_movement (id serial primary key, operation_date timestamp, type varchar(255), value double, destination_id integer, origin_id integer, primary key (id));
create table city (id serial primary key, name varchar(255), state_id integer, primary key (id));
create table clinic (cnpj varchar(255), id integer not null, primary key (id));
create table clinic_specialties (clinic_id integer not null, specialties_id integer not null);
create table credit (id serial primary key, balance double, user_id integer, primary key (id));
create table customer (cpf varchar(255), id integer not null, primary key (id));
create table feedback (id serial primary key, message varchar(255), rating integer, clinic_id integer, customer_id integer, primary key (id));
create table phones (user_id integer not null, phones varchar(255));
create table profiles (user_id integer not null, profiles integer);
create table specialty (id serial primary key, name varchar(255), primary key (id));
create table state (id serial primary key, name varchar(255), primary key (id));
create table user (id serial primary key, email varchar(255), name varchar(255), password varchar(255), primary key (id));
alter table address add constraint FKpo044ng5x4gynb291cv24vtea foreign key (city_id) references city;
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user;
alter table balance_movement add constraint FKcmkmprbsvfg4qa86pybcc6gsk foreign key (destination_id) references credit;
alter table balance_movement add constraint FKf7gvcyiosdifrwd7cbhdwx9kp foreign key (origin_id) references credit;
alter table city add constraint FK6p2u50v8fg2y0js6djc6xanit foreign key (state_id) references state;
alter table clinic add constraint FKqppyswwa2hwir71rlfji8qod0 foreign key (id) references user;
alter table clinic_specialties add constraint FKp6cljllrennlqouau9gl5hw1j foreign key (specialties_id) references specialty;
alter table clinic_specialties add constraint FKk4yp8k5g07qplfbrit6la6l3u foreign key (clinic_id) references clinic;
alter table credit add constraint FKruqa8y0rd9lldy1mcwq78shlv foreign key (user_id) references user;
alter table customer add constraint FKg2o3t8h0g17smtr9jgypagdtv foreign key (id) references user;
alter table feedback add constraint FKn71kqrs008jxpk30y1k0yjor5 foreign key (clinic_id) references clinic;
alter table feedback add constraint FKpi2y2j7n01ypo49fone3knjry foreign key (customer_id) references customer;
alter table phones add constraint FKgund2v0m0j3bbxf1bbvvbvjyi foreign key (user_id) references user;
alter table profiles add constraint FKkp1llevr3n7k8815sjtios7me foreign key (user_id) references user;