DROP ALL OBJECTS;

create table address (id serial, complement varchar(255), latitude varchar(255), longitude varchar(255), neighborhood varchar(255), number varchar(255), public_area varchar(255), city varchar(255), state varchar(255), zip_code varchar(255), user_id integer, primary key (id));
create table balance_movement (id serial, operation_date timestamp, type varchar(255), value double, destination_id integer, origin_id integer, status varchar(255), primary key (id));
create table clinic (cnpj varchar(255), id integer not null, primary key (id));
create table clinic_specialties (clinic_id integer not null, specialty_id integer not null, appointment_value double);
create table credit (id serial, balance double, user_id integer, primary key (id));
create table customer (cpf varchar(255), id integer not null, primary key (id));
create table feedback (id serial, message varchar(255), rating double, clinic_id integer, customer_id integer, primary key (id));
create table phones (user_id integer not null, phones varchar(255));
create table profiles (user_id integer not null, profile_id integer);
create table specialty (id serial, name varchar(255), primary key (id));
create table email (id serial, ownerRef varchar(255), emailFrom varchar(255), emailTo varchar(255), text text, sendDateEmail date, statusEmail integer, primary key (id));
create table tb_user (id serial, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table scheduling (id serial, customer_id integer, clinic_id integer, specialty_id integer, scheduled_to timestamp, appointment_value double, appointment_time varchar(10), primary key (id));

alter table address add constraint fk_address_user foreign key (user_id) references tb_user(id);
alter table balance_movement add constraint fk_balance_mov_credit_dest foreign key (destination_id) references credit;
alter table balance_movement add constraint fk_balance_mov_credit_orig foreign key (origin_id) references credit;
alter table clinic add constraint fk_clinic_user foreign key (id) references tb_user(id);
alter table clinic_specialties add constraint fk_clic_specialt_specialty foreign key (specialty_id) references specialty;
alter table clinic_specialties add constraint fk_clic_specialt_clinic foreign key (clinic_id) references tb_user;
alter table credit add constraint fk_credit_user foreign key (user_id) references tb_user(id);
alter table customer add constraint fk_customer_user foreign key (id) references tb_user(id);
alter table feedback add constraint fk_feedback_clinic foreign key (clinic_id) references clinic;
alter table feedback add constraint fk_feedback_customer foreign key (customer_id) references customer;
alter table phones add constraint fk_phones_user foreign key (user_id) references tb_user(id);
alter table profiles add constraint fk_profiles_user foreign key (user_id) references tb_user(id);
alter table tb_user add constraint uk_user_email unique(email);
alter table clinic add constraint uk_clinic_cnpj unique(cnpj);
alter table customer add constraint uk_customer_cpf unique(cpf);
alter table scheduling add constraint fk_scheduling_customer foreign key (customer_id) references customer;
alter table scheduling add constraint fk_scheduling_clinic foreign key (clinic_id) references clinic;
alter table scheduling add constraint fk_scheduling_specialty foreign key (specialty_id) references specialty;